stages:
  preprocessing:
    cmd: python preprocessing.py
    deps:
    - heart.csv
    - preprocessing.py
    outs:
    - train_data.csv
    - test_data.csv
  train:
    cmd: python train.py
    deps:
    - train.py
    - train_data.csv
    outs:
    - confusion_matrix.png
    - model.pkl
    metrics:
    - metrics.json:
        cache: false

  test:
    cmd: python test.py
    deps:
    - test.py
    - test_data.csv
    - model.pkl
    outs:
    - test_confusion_matrix.png
    metrics:
    - test_metrics.json:
        cache: false

  feature_importance:
    cmd: python feature_importance.py
    deps:
    - feature_importance.py
    - test_data.csv
    - model.pkl
    outs:
    - feature_importance.png
